export const CatData1 = {
    text1: "Kitchen",
    text2: "Pots and Pans",
    text3: "Coffee Maker",
    text4: "Steam Cleaner and Iron",
    text5: "Refrigerator and Freezer",
    text6: "Electronics",
    text7: "Mobile",
    text8: "Mobile Accessories",
    text9: "Laptop",
    text10: "Laptop Accessories",
    text11: "Computer Parts",
    text12: "Stationery",
    text13: "Writing Tools",
    text14: "Paper",
    text15: "Clothing",
    text16: "T-Shirt",
    text17: "Shoes",
    text18: "Pants",
    text19: "All Products",
};
